### ISSUE TITLE
Compiler errors in Unity v2020

### ISSUE THREAD

**Issue by LiterallyAKing** [Skyrim07/SKCell#2]
Hello! After importing, I'm getting six compiler errors, this is in Unity2020.3.33. Two are from referring to `EditorGUIUtility.SetIconForObject`, and four for referring to `UnityEditor.SceneManagement.PrefabStageUtility`. So I'm guessing those both were added in later versions.

I wouldn't necessarily assume an older version was supported, but since you're targeting 2017.x+ thought I'd mention it.

Here's one of the error messages for each reference:

```
Assets\SKCell\Editor\Hierarchy\SKHierarchy.cs(296,34): error CS0117: 'EditorGUIUtility' does not contain a definition for 'SetIconForObject'
```
```
Assets\SKCell\Editor\UI_Comp\SKToggleEditor.cs(20,44): error CS0234: The type or namespace name 'PrefabStageUtility' does not exist in the namespace 'UnityEditor.SceneManagement' (are you missing an assembly reference?)
```

**Comment by Skyrim07** [comment]
Thanks for the issue! I was planning to support Unity 2017 and newer before v0.13, but as you pointed out, some of the APIs I used after v0.13 are not available in Unity 2020 and older. 
I will change the version requirement to Unity 2021.x and newer.

**Comment by LiterallyAKing** [comment]
And I can confirm it works just fine in 2021.x, so makes sense!
