### ISSUE TITLE
资产包案例项目下SKConsole_Demo.cs类名似乎是有错误，Demo写成了Dsemo，导致控制台使用案例无法正常运行

### ISSUE THREAD

**Issue by ghost** [Skyrim07/SKCell#3]
<img width="706" alt="Snipaste_2023-12-18_16-24-57" src="https://github.com/Skyrim07/SKCell/assets/40449842/bdc5bb8c-c142-4503-8ca2-c006cdd4ee93">

**Comment by Skyrim07** [comment]
Thanks! Resolved in v1.2.4
